output_dir: ~/scratch/torchprotein_output/

dataset:
  class: BetaLactamase
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
    readout: mean
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  normalization: False
  num_mlp_layer: 2

eval_metric: spearmanr

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 32

train:
  num_epoch: 100