output_dir: ~/scratch/torchprotein_output/

dataset:
  class: YeastPPI
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ProteinConvolutionalNetwork
    input_dim: 21
    hidden_dims: [1024, 1024]
    kernel_size: 5
    padding: 2
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0]
  batch_size: 256

train:
  num_epoch: 100