output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: BinaryLocalization
    path: ~/scratch/protein-datasets/
    residue_only: True
    center: True
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    residue_only: True
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
          residue: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 2 ]
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 1195 ]

model:
  class: ConvolutionalNetwork
  input_dim: 21
  hidden_dims: [1024, 1024]
  kernel_size: 5
  padding: 2

eval_metric: Center - BinaryLocalization accuracy

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
  tradeoff: 1.0